spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client id
            client-secret: client secret
  data:
    mongodb:
      host: localhost
      port: 27017
#      uri: uri
      database: database
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: key

#logging:
#  level:
#    com:
#      example:
#        JournalApplication: ERROR

#server:
#  port: 8080
#  servlet:
#    context-path: /journal